version: "3.8"
services:
  my_streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: poetry run streamlit run app3.py
